# Generated by Django 5.0.6 on 2026-03-16 15:14

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero_transaccion",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "tipo_pago",
                    models.CharField(
                        choices=[
                            ("alquiler", "Pago de Alquiler"),
                            ("deposito", "Depósito de Garantía"),
                            ("adicional", "Cargo Adicional"),
                            ("reembolso", "Reembolso"),
                        ],
                        default="alquiler",
                        max_length=20,
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta_credito", "Tarjeta de Crédito"),
                            ("tarjeta_debito", "Tarjeta de Débito"),
                            ("transferencia", "Transferencia Bancaria"),
                            ("paypal", "PayPal"),
                            ("stripe", "Stripe"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("procesando", "Procesando"),
                            ("completado", "Completado"),
                            ("fallido", "Fallido"),
                            ("reembolsado", "Reembolsado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_pago", models.DateTimeField(auto_now_add=True)),
                ("fecha_procesado", models.DateTimeField(blank=True, null=True)),
                ("referencia_externa", models.CharField(blank=True, max_length=200)),
                ("notas", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-fecha_pago"],
            },
        ),
    ]
