# Generated by Django 5.0.6 on 2026-03-16 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pagos", "0001_initial"),
        ("reservas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="reserva",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pagos",
                to="reservas.reserva",
            ),
        ),
    ]
