# Generated by Django 5.0.6 on 2026-03-16 15:14

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero_reserva",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("fecha_entrega_real", models.DateTimeField(blank=True, null=True)),
                ("fecha_devolucion_real", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de Confirmación"),
                            ("confirmada", "Confirmada"),
                            ("en_curso", "En Curso"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                            ("vencida", "Vencida"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "costo_alquiler",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "deposito_pagado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "costo_adicional",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("notas_cliente", models.TextField(blank=True)),
                ("notas_admin", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmada_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
