# Generated by Django 5.0.6 on 2026-03-16 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipos", "0001_initial"),
        ("reservas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="cliente",
            field=models.ForeignKey(
                limit_choices_to={"tipo_usuario": "cliente"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reserva",
            name="equipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservas",
                to="equipos.equipo",
            ),
        ),
    ]
