# Generated by Django 5.0.6 on 2026-03-16 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipos", "0001_initial"),
        ("reservas", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalificacionEquipo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("puntuacion", models.PositiveSmallIntegerField()),
                ("comentario", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("reserva_confirmada", "Reserva confirmada"),
                            ("recordatorio_entrega", "Recordatorio de entrega"),
                            ("recordatorio_devolucion", "Recordatorio de devolución"),
                        ],
                        max_length=40,
                    ),
                ),
                ("mensaje", models.CharField(max_length=255)),
                ("fecha_programada", models.DateTimeField()),
                ("enviado", models.BooleanField(default=False)),
                ("enviado_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["fecha_programada"],
            },
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(
                fields=["cliente", "estado"], name="reservas_re_cliente_5b00f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(
                fields=["equipo", "fecha_inicio", "fecha_fin"],
                name="reservas_re_equipo__81629c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(
                fields=["numero_reserva"], name="reservas_re_numero__186cfa_idx"
            ),
        ),
        migrations.AddField(
            model_name="calificacionequipo",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calificaciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="calificacionequipo",
            name="equipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calificaciones",
                to="equipos.equipo",
            ),
        ),
        migrations.AddField(
            model_name="calificacionequipo",
            name="reserva",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calificacion",
                to="reservas.reserva",
            ),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="reserva",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notificaciones",
                to="reservas.reserva",
            ),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notificaciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["enviado", "fecha_programada"],
                name="reservas_no_enviado_2754fa_idx",
            ),
        ),
    ]
